# COMPILER SETTINGS

if(NOT DEFINED CMAKE_CXX_STANDARD)
    set(CMAKE_CXX_STANDARD 11)
endif()

if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(CMAKE_C_FLAGS_DEBUG "-g -O0 -DDEBUG -Wall" CACHE STRING "")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "-g -O2" CACHE STRING "")
    set(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "")
    set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "")

    set(CMAKE_CXX_FLAGS_DEBUG "-g -O0 -DDEBUG -Wall" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -O2" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "")

    set(CMAKE_EXE_LINKER_FLAGS_DEBUG "-g" CACHE STRING "")
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "-g" CACHE STRING "")

    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "-g" CACHE STRING "")
    set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "-g" CACHE STRING "")

    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "-g" CACHE STRING "")
    set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "-g" CACHE STRING "")
elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(CMAKE_C_FLAGS_DEBUG "-g -O0 -DDEBUG -Wall" CACHE STRING "")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "-g -O2" CACHE STRING "")
    set(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "")
    set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "")

    set(CMAKE_CXX_FLAGS_DEBUG "-g -O0 -DDEBUG -Wall" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-g -O2" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "")

    set(CMAKE_EXE_LINKER_FLAGS_DEBUG "-g" CACHE STRING "")
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "-g" CACHE STRING "")

    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "-g" CACHE STRING "")
    set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "-g" CACHE STRING "")

    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "-g" CACHE STRING "")
    set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "-g" CACHE STRING "")
endif()

# DELUA SETTINGS

if(NOT DEFINED LUA_LANGUAGE_INIT)
    set(LUA_LANGUAGE_INIT C)
endif()

if(NOT DEFINED LUA_PROGNAME_INIT)
    set(LUA_PROGNAME_INIT "delua")
endif()

if(NOT DEFINED LUA_SYMBOLIC_LINK_INIT)
    set(LUA_SYMBOLIC_LINK_INIT FALSE)
endif()

# BUILD SETTINGS

if(NOT DEFINED LUA_BUILD_STATIC_INIT)
    set(LUA_BUILD_STATIC_INIT ON)
endif()

if(NOT DEFINED LUA_BUILD_SHARED_INIT)
    set(LUA_BUILD_SHARED_INIT ON)
endif()

if(NOT DEFINED LUA_BUILD_INTERPRETER_INIT)
    set(LUA_BUILD_INTERPRETER_INIT ON)
endif()

if(NOT DEFINED LUA_BUILD_COMPILER_INIT)
    set(LUA_BUILD_COMPILER_INIT ON)
endif()

if(NOT DEFINED LUA_LANGUAGE_C_INIT)
    set(LUA_LANGUAGE_C_INIT ON)
endif()

if(NOT DEFINED LUA_LANGUAGE_CXX_INIT)
    set(LUA_LANGUAGE_CXX_INIT ON)
endif()

