set(CMAKE_BUILD_TYPE_INIT "Debug") # RelWithDebInfo

if (CMAKE_COMPILER_IS_GNUCXX)
    set(CMAKE_CXX_FLAGS_DEBUG_INIT "-ggdb3 -O0 -DDEBUG -Wall")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-ggdb3 -O2")
    set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Os -DNDEBUG")
    set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")

    set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO_INIT "-ggdb3")

    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO_INIT "-ggdb3")

    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO_INIT "-ggdb3")
endif(CMAKE_COMPILER_IS_GNUCXX)
