include($ENV{HOME}/.local/share/cmake-${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}/Modules/LocalInitFlags.cmake OPTIONAL)

# DELUA SETTINGS

if(NOT DEFINED LUA_LANGUAGE_INIT)
    set(LUA_LANGUAGE_INIT C)
endif(NOT DEFINED LUA_LANGUAGE_INIT)

if(NOT DEFINED LUA_NAME_INIT)
    set(LUA_NAME_INIT "lua")
endif(NOT DEFINED LUA_NAME_INIT)

if(WINDOWS AND NOT UNIX)
    if(NOT DEFINED LUA_USE_C89_INIT)
        set(LUA_USE_C89_INIT OFF)
    endif(NOT DEFINED LUA_USE_C89_INIT)
    set(LUA_USE_WINDOWS true CACHE INTERNAL "Visual Studio compat.")
    set(LUA_DL_DLL true CACHE INTERNAL "Windows DLL support.")
endif(WINDOWS AND NOT UNIX)

# BUILD SETTINGS
setundef(LUA_BUILD_STATIC_INIT ON)
setundef(LUA_BUILD_SHARED_INIT ON)
setundef(LUA_BUILD_INTERPRETER_INIT ON)
setundef(LUA_BUILD_COMPILER_INIT ON)
