set(CMAKE_BUILD_TYPE_INIT "Debug") # RelWithDebInfo

set(CMAKE_CXX_STANDARD 11)

if (CMAKE_COMPILER_IS_GNUCXX)
    set(CMAKE_C_FLAGS_DEBUG_INIT "-ggdb3 -O0 -DDEBUG -Wall")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-ggdb3 -O2")
    set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-Os -DNDEBUG")
    set(CMAKE_C_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")

    set(CMAKE_CXX_FLAGS_DEBUG_INIT "-ggdb3 -O0 -DDEBUG -Wall")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-ggdb3 -O2")
    set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Os -DNDEBUG")
    set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")

    set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO_INIT "-ggdb3")

    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO_INIT "-ggdb3")

    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO_INIT "-ggdb3")
endif(CMAKE_COMPILER_IS_GNUCXX)

if(NOT DEFINED LUA_CXX_INIT)
    set(LUA_CXX_INIT false)
endif(NOT DEFINED LUA_CXX_INIT)

if(NOT DEFINED LUA_NAME_INIT)
    set(LUA_NAME_INIT "lua")
endif(NOT DEFINED LUA_NAME_INIT)

if(WINDOWS AND NOT UNIX)
    if(NOT DEFINED LUA_USE_C89_INIT)
        set(LUA_USE_C89_INIT OFF)
    endif(NOT DEFINED LUA_USE_C89_INIT)
    set(LUA_USE_WINDOWS true CACHE INTERNAL "Visual Studio compat.")
    set(LUA_DL_DLL true CACHE INTERNAL "Windows DLL support.")
endif(WINDOWS AND NOT UNIX)
